### ISSUE TITLE
issues installing via nuget

### ISSUE THREAD

**Issue by Jezternz** [salmonthinlion/GoogleCloudPrintApi#1]
Hi,

Thankyou for providing this great library, it looks like it does everything I would need bar subscribing to events from google (I am going to look into implementing myself).

I am having some trouble installing it via nuget, I get the following error:
```
PM> Install-Package GoogleCloudPrintApi
Installing 'GoogleCloudPrintApi 1.0.4'.
Successfully installed 'GoogleCloudPrintApi 1.0.4'.
Adding 'GoogleCloudPrintApi 1.0.4' to <PROJECT_NAME>.
Uninstalling 'GoogleCloudPrintApi 1.0.4'.
Successfully uninstalled 'GoogleCloudPrintApi 1.0.4'.
Install failed. Rolling back...
Install-Package : Could not install package 'GoogleCloudPrintApi 1.0.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  GoogleCloudPrintApi
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

Not sure if I am doing something silly, but I tried 4.5 & 4.5.1 to no avail.

**Comment by Jezternz** [comment]
Worked it out, an upgrade from VS2k12 to VS2k15 and moving project to .net4.61 seemed to do the trick.

**Comment by salmonthinlion** [comment]
Hi, @Jezternz, you're welcome! Happy to see it's useful to you.

**Comment by jonathansmirnoff** [comment]
Hi Guys! I have the same issue but I'm working with xamarin studio in MAC OS. I think I don't have the chance to install .NET 4.61. Do you have a work around to fix this issue? Thanks!

**Comment by salmonthinlion** [comment]
Hi @jonathansmirnoff, I suppose you are talking about working on a .NET Framework 4.6 project on xamarin studio and unrelated to anything about xamarin mobile. 

If it's the case, you can install another package called "GoogleCloudPrintApi.Net452" on Nuget, it should support .NET Framework 4.5.2 or above.

**Comment by jonathansmirnoff** [comment]
Yes, I saw it. The problem is that last version of xamarin for mac works with 4.5.1 :( 
I think that I have to wait a bit :)
