### ISSUE TITLE
Problems with creating a "virtual" printer.

### ISSUE THREAD

**Issue by Jezternz** [salmonthinlion/GoogleCloudPrintApi#2]
I seem to be having a bit of trouble creating a virtual printer, I have seen in your examples you use a real printer and use the method "GetCapabilitiesFromPrintQueue(pq);" to retrieve its capabilities, however for my purposes I need to be able to define my own "virtual" printer, with all capabilities.

I have tried the code below and it fails (which is fine), however the "Success" flag is set to false, as expected but I have no way to debug the problem, no exception is thrown or error message is included in the "response" object.

Do you have any suggestions to tweak this code to make it work or possibly retrieve an error message?

Simple:
```
var request = new RegisterRequest
{
    Name = "CloudPrinter1"
};
var response = await gcp.RegisterPrinterAsync(request);
Console.WriteLine("{0}", response.Success); // false
```

With empty capabilities:
```
var request = new RegisterRequest
{
    Name = "CloudPrinter1",
    DefaultDisplayName = ".CloudPrinter1",
    Capabilities = "{}"
};
var response = await gcp.RegisterPrinterAsync(request);
Console.WriteLine("{0}", response.Success); // false
```

Cheers,
J

**Comment by salmonthinlion** [comment]
Hi J,

According to [/register interface for Google Cloud Print](https://developers.google.com/cloud-print/docs/proxyinterfaces#register), capabilities is required for printer registration. You must include the capabilities no matter your printer is a real one or a virtual one. 

However, capabilities is mainly used for specifying how the printer is capable of, you can just fake it by retrieving a printer capability from any printer you created in your control panel. If you want, you can even modify the capability you retrieved before passing to Google to ensure all the capabilities are supported but you may need a knowledge in modifying the capability XPS document however.

For the error message part, you are right, i have missed some error handling in my code. It may be fixed on a couple of days, I will publish the nuget package once it's completed.

Best,
Karl

**Comment by Jezternz** [comment]
Perfect, Thanks Karl, I will repost here when I have worked out what works.

**Comment by Jezternz** [comment]
For anyone in future stumbling across this, I was able to get it working using the CDD example found here: https://developers.google.com/cloud-print/docs/cdd#cdd

Register "Dummy" printer code:
```
var request = new RegisterRequest{ Name = "Printer 1", UseCdd = true, Capabilities = CDD_TEXT, Proxy = "PROXY_ID" };
var response = await gcp.RegisterPrinterAsync(request);
```

Full CDD code:
```
{
  "version": "1.0",
  "printer": {
    "supported_content_type": [
      {"content_type": "application/pdf", "min_version": "1.5"},
      {"content_type": "image/jpeg"},
      {"content_type": "text/plain"}
    ],
    "input_tray_unit": [
      {
        "vendor_id": "tray",
        "type": "INPUT_TRAY"
      }
    ],
    "marker": [
      {
        "vendor_id": "black",
        "type": "INK",
        "color": {"type": "BLACK"}
      },
      {
        "vendor_id": "color",
        "type": "INK",
        "color": {"type": "COLOR"}
      }
    ],
    "cover": [
      {
        "vendor_id": "front",
        "type": "CUSTOM",
        "custom_display_name": "front cover"
      }
    ],
    "vendor_capability": [],
    "color": {
      "option": [
        {"type": "STANDARD_MONOCHROME"},
        {"type": "STANDARD_COLOR", "is_default": true},
        {
          "vendor_id": "ultra-color",
          "type": "CUSTOM_COLOR",
          "custom_display_name": "Best Color"
        }
      ]
    },
    "copies": {
      "default": 1,
      "max": 100
    },
    "media_size": {
      "option": [
        {
          "name": "ISO_A4",
          "width_microns": 210000,
          "height_microns": 297000,
          "is_default": true
        },
        {
          "name": "NA_LEGAL",
          "width_microns": 215900,
          "height_microns": 355600
        },
        {
          "name": "NA_LETTER",
          "width_microns": 215900,
          "height_microns": 279400
        }
      ]
    }
  }
}
```
