### ISSUE TITLE
How to retrieve finishing options

### ISSUE THREAD

**Issue by Jezternz** [salmonthinlion/GoogleCloudPrintApi#6]
Hey Karl,

I seem to have no end of issues for you ;)

I have hit a small hitch where I am trying to retrieve the (1) number of copies and (2) color setting, depending on what the user has set (see the image example below).

I looked through the google cloud print api (https://developers.google.com/cloud-print/docs/appInterfaces) and couldn't find any information on how I could get these user-set settings.

I also figured that maybe that was the intention of the "GetTicketAsync" method. However when I try to use GetTicketAsync() method I get an InnerException with:
` Data at the root level is invalid. Line 1, position 1.`

I have also tried GetTicketv2Async() but get a different exception (which is a bit confusing because I am using CDD to define my printer, I guess it is expecting an older CDD?).
`Use GCP 1.0 instead since GCP 2.0 requires CDD document for the printer`

Thanks again for your time :)

user option input example:
<img src="https://cloud.githubusercontent.com/assets/987884/21406461/e69d08bc-c81f-11e6-9afb-cdc9e33ec20b.png" height="300">

**Comment by salmonthinlion** [comment]
Hi J,

Your guess is correct, the GetTicketAsync & GetTicketv2Async is intended for retrieving user settings for the print job for printers using XPS/CDD respectively. 

However, this library was developed based on Google Cloud Print 1.0 which mainly uses the XPS format. I have not yet completed the GetTicketv2Async for retrieving settings for CDD print jobs but I am working on it now, it may take 1-2 days for the implementation. The code will be updated once it's completed.

Best,
Karl

**Comment by Jezternz** [comment]
Awesome, thanks Karl.

**Comment by salmonthinlion** [comment]
Hi J,

The code is commited, please use the following and see if it works, thanks!

var request = new TicketRequest
{
    JobId = printJob.Id
};
var ticket = await client.GetCloudJobTicketAsync(request);

Karl

**Comment by Jezternz** [comment]
Thanks Karl,

Tested and confirmed working. PageRange didn't seem to come across, and I was unable to find Paper Size settings, however for the primary use cases (color/copies) it is working fine.

Cheers,
Josh

**Comment by salmonthinlion** [comment]
Hi J,

Thanks for your help! 

For some properties like PageRange, Google has directly applied the settings to the document. As you may notice, if page range is set to 1-2 pages, the downloaded document will just return the 2 pages you have selected from the option but it turns out the "pagerange" property to be null. I don't know the intention of that but it seems it's the case.

For Paper Size settings, it is converted to MediaSize property defined by Google. You may find HeightMicrons & WidthMicrons there representing the Paper Size. For instance, ISO_A4 is represented by 297000 * 210000.

Best,
Karl

**Comment by Jezternz** [comment]
Thanks for the explanation Karl, have a great new year :)

**Comment by salmonthinlion** [comment]
You too :)
